// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SalesHub.Infrastructure.Persistence;

#nullable disable

namespace SalesHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429225526_AddLocalities")]
    partial class AddLocalities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.ApifyRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ApifyRunId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("apify_run_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("InputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_json");

                    b.Property<int>("ItemsCount")
                        .HasColumnType("integer")
                        .HasColumnName("items_count");

                    b.Property<int>("LeadsCreated")
                        .HasColumnType("integer")
                        .HasColumnName("leads_created");

                    b.Property<string>("ProductKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("product_key");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_apify_runs");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_apify_runs_started_at");

                    b.ToTable("apify_runs", (string)null);
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.CityQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("country");

                    b.Property<int?>("GeonameId")
                        .HasColumnType("integer")
                        .HasColumnName("geoname_id");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<int?>("Population")
                        .HasColumnType("integer")
                        .HasColumnName("population");

                    b.Property<int>("PopulationBucket")
                        .HasColumnType("integer")
                        .HasColumnName("population_bucket");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("province");

                    b.HasKey("Id")
                        .HasName("pk_cities_queue");

                    b.HasIndex("GeonameId")
                        .HasDatabaseName("ix_cities_queue_geoname_id");

                    b.HasIndex("Country", "PopulationBucket")
                        .HasDatabaseName("ix_cities_queue_country_population_bucket");

                    b.HasIndex("Country", "Province", "City")
                        .IsUnique()
                        .HasDatabaseName("ix_cities_queue_country_province_city");

                    b.ToTable("cities_queue", (string)null);
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.Competitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<int?>("FollowersCount")
                        .HasColumnType("integer")
                        .HasColumnName("followers_count");

                    b.Property<int?>("FollowingCount")
                        .HasColumnType("integer")
                        .HasColumnName("following_count");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("handle");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastScrapedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scraped_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("platform");

                    b.Property<int?>("PostsCount")
                        .HasColumnType("integer")
                        .HasColumnName("posts_count");

                    b.Property<string>("RawProfileJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_profile_json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vertical")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("vertical");

                    b.HasKey("Id")
                        .HasName("pk_competitors");

                    b.HasIndex("Platform", "Handle")
                        .IsUnique()
                        .HasDatabaseName("ix_competitors_platform_handle");

                    b.ToTable("competitors", (string)null);
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.CompetitorComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorHandle")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("author_handle");

                    b.Property<bool>("IsNegative")
                        .HasColumnType("boolean")
                        .HasColumnName("is_negative");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<string>("RawJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_competitor_comments");

                    b.HasIndex("IsNegative")
                        .HasDatabaseName("ix_competitor_comments_is_negative");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_competitor_comments_post_id");

                    b.ToTable("competitor_comments", (string)null);
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.CompetitorPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<int>("CommentsCount")
                        .HasColumnType("integer")
                        .HasColumnName("comments_count");

                    b.Property<Guid>("CompetitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("competitor_id");

                    b.Property<string>("ExternalPostId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_post_id");

                    b.Property<List<string>>("Hashtags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("hashtags");

                    b.Property<int>("Likes")
                        .HasColumnType("integer")
                        .HasColumnName("likes");

                    b.Property<string>("PostUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("post_url");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<string>("RawJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<DateTimeOffset>("ScrapedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scraped_at");

                    b.HasKey("Id")
                        .HasName("pk_competitor_posts");

                    b.HasIndex("CompetitorId", "ExternalPostId")
                        .IsUnique()
                        .HasDatabaseName("ix_competitor_posts_competitor_id_external_post_id");

                    b.ToTable("competitor_posts", (string)null);
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<string>("EvolutionInstance")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("evolution_instance");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("RawJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("WhatsappMessageId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("whatsapp_message_id");

                    b.HasKey("Id")
                        .HasName("pk_conversation_messages");

                    b.HasIndex("WhatsappMessageId")
                        .HasDatabaseName("ix_conversation_messages_whatsapp_message_id");

                    b.HasIndex("LeadId", "Timestamp")
                        .HasDatabaseName("ix_conversation_messages_lead_id_timestamp");

                    b.HasIndex("SellerId", "IsRead", "Direction")
                        .HasDatabaseName("ix_conversation_messages_seller_id_is_read_direction");

                    b.ToTable("conversation_messages", (string)null);
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.EvolutionInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at");

                    b.Property<string>("ConnectedPhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("connected_phone_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DisconnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disconnected_at");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("instance_name");

                    b.Property<string>("LastQrCodeBase64")
                        .HasColumnType("text")
                        .HasColumnName("last_qr_code_base64");

                    b.Property<DateTimeOffset?>("LastStatusCheckAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_status_check_at");

                    b.Property<DateTimeOffset?>("QrCodeGeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("qr_code_generated_at");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_evolution_instances");

                    b.HasIndex("InstanceName")
                        .IsUnique()
                        .HasDatabaseName("ix_evolution_instances_instance_name");

                    b.HasIndex("SellerId")
                        .IsUnique()
                        .HasDatabaseName("ix_evolution_instances_seller_id");

                    b.ToTable("evolution_instances", (string)null);
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("BusinessStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("business_status");

                    b.Property<string>("City")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("facebook_url");

                    b.Property<DateTimeOffset?>("FirstReplyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_reply_at");

                    b.Property<string>("InstagramHandle")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("instagram_handle");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PlaceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("place_id");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("product_key");

                    b.Property<string>("Province")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("province");

                    b.Property<DateTimeOffset?>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<string>("RawDataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data_json");

                    b.Property<string>("RawPhone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("raw_phone");

                    b.Property<string>("RenderedMessage")
                        .HasColumnType("text")
                        .HasColumnName("rendered_message");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("SearchCategory")
                        .HasColumnType("text")
                        .HasColumnName("search_category");

                    b.Property<string>("SearchQuery")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("search_query");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("TotalReviews")
                        .HasColumnType("integer")
                        .HasColumnName("total_reviews");

                    b.Property<List<string>>("Types")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("types");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("website");

                    b.Property<string>("WhatsappJid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("whatsapp_jid");

                    b.Property<string>("WhatsappLink")
                        .HasColumnType("text")
                        .HasColumnName("whatsapp_link");

                    b.Property<string>("WhatsappPhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("whatsapp_phone");

                    b.Property<bool>("WhatsappValidated")
                        .HasColumnType("boolean")
                        .HasColumnName("whatsapp_validated");

                    b.HasKey("Id")
                        .HasName("pk_leads");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_leads_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_leads_status");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("ix_leads_latitude_longitude");

                    b.HasIndex("ProductKey", "PlaceId")
                        .HasDatabaseName("ix_leads_product_key_place_id")
                        .HasFilter("place_id IS NOT NULL");

                    b.HasIndex("ProductKey", "WhatsappPhone")
                        .IsUnique()
                        .HasDatabaseName("ix_leads_product_key_whatsapp_phone")
                        .HasFilter("whatsapp_phone IS NOT NULL");

                    b.HasIndex("SellerId", "Status")
                        .HasDatabaseName("ix_leads_seller_id_status");

                    b.ToTable("leads", (string)null);
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.Locality", b =>
                {
                    b.Property<string>("Gid2")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gid2");

                    b.Property<string>("AdminLevel1Gid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("admin_level1gid");

                    b.Property<string>("AdminLevel1Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("admin_level1name");

                    b.Property<double>("CentroidLat")
                        .HasColumnType("double precision")
                        .HasColumnName("centroid_lat");

                    b.Property<double>("CentroidLng")
                        .HasColumnType("double precision")
                        .HasColumnName("centroid_lng");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("country_code");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("country_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.HasKey("Gid2")
                        .HasName("pk_localities");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("ix_localities_country_code");

                    b.HasIndex("CountryCode", "AdminLevel1Gid")
                        .HasDatabaseName("ix_localities_country_code_admin_level1gid");

                    b.ToTable("localities", (string)null);
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.MessageOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("EvolutionInstance")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("evolution_instance");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("WhatsappPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("whatsapp_phone");

                    b.HasKey("Id")
                        .HasName("pk_message_outbox");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_message_outbox_lead_id");

                    b.HasIndex("Status", "ScheduledAt")
                        .HasDatabaseName("ix_message_outbox_status_scheduled_at");

                    b.HasIndex("SellerId", "Status", "ScheduledAt")
                        .HasDatabaseName("ix_message_outbox_seller_id_status_scheduled_at");

                    b.ToTable("message_outbox", (string)null);
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<List<string>>("Categories")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("categories");

                    b.Property<string>("CheckoutUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("checkout_url");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("country");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("country_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DailyLimit")
                        .HasColumnType("integer")
                        .HasColumnName("daily_limit");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<int>("GooglePlacesDailyLeadCap")
                        .HasColumnType("integer")
                        .HasColumnName("google_places_daily_lead_cap");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_template");

                    b.Property<string>("PhonePrefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("phone_prefix");

                    b.Property<string>("PriceDisplay")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("price_display");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("product_key");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("region_code");

                    b.Property<bool>("RequiresAssistedSale")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_assisted_sale");

                    b.Property<List<int>>("TriggerHours")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("trigger_hours");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasAlternateKey("ProductKey")
                        .HasName("ak_products_product_key");

                    b.HasIndex("ProductKey")
                        .IsUnique()
                        .HasDatabaseName("ix_products_product_key");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.ScrapeLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("category");

                    b.Property<string>("City")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("country");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("product_key");

                    b.Property<int>("ResultsCount")
                        .HasColumnType("integer")
                        .HasColumnName("results_count");

                    b.Property<DateTimeOffset>("RunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_at");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_scrape_log");

                    b.HasIndex("ProductKey", "City", "Category", "RunAt")
                        .HasDatabaseName("ix_scrape_log_product_key_city_category_run_at");

                    b.ToTable("scrape_log", (string)null);
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActiveHoursEnd")
                        .HasColumnType("integer")
                        .HasColumnName("active_hours_end");

                    b.Property<int>("ActiveHoursStart")
                        .HasColumnType("integer")
                        .HasColumnName("active_hours_start");

                    b.Property<int>("BurstPauseMaxSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("burst_pause_max_seconds");

                    b.Property<int>("BurstPauseMinSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("burst_pause_min_seconds");

                    b.Property<int>("BurstSize")
                        .HasColumnType("integer")
                        .HasColumnName("burst_size");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DailyCap")
                        .HasColumnType("integer")
                        .HasColumnName("daily_cap");

                    b.Property<int>("DailyVariancePct")
                        .HasColumnType("integer")
                        .HasColumnName("daily_variance_pct");

                    b.Property<int>("DelayMaxSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("delay_max_seconds");

                    b.Property<int>("DelayMinSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("delay_min_seconds");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleSubject")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("google_subject");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<int>("PreSendTypingMaxSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("pre_send_typing_max_seconds");

                    b.Property<int>("PreSendTypingMinSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("pre_send_typing_min_seconds");

                    b.Property<bool>("ReadIncomingFirst")
                        .HasColumnType("boolean")
                        .HasColumnName("read_incoming_first");

                    b.Property<List<string>>("RegionsAssigned")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("regions_assigned");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("SellerKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("seller_key");

                    b.Property<int>("SendMode")
                        .HasColumnType("integer")
                        .HasColumnName("send_mode");

                    b.Property<bool>("SendingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("sending_enabled");

                    b.Property<int>("SkipDayProbabilityPct")
                        .HasColumnType("integer")
                        .HasColumnName("skip_day_probability_pct");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<int>("TypoProbabilityPct")
                        .HasColumnType("integer")
                        .HasColumnName("typo_probability_pct");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<List<string>>("VerticalsWhitelist")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("verticals_whitelist");

                    b.Property<int>("WarmupDays")
                        .HasColumnType("integer")
                        .HasColumnName("warmup_days");

                    b.Property<DateTimeOffset?>("WarmupStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("warmup_started_at");

                    b.Property<string>("WhatsappPhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("whatsapp_phone");

                    b.HasKey("Id")
                        .HasName("pk_sellers");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_sellers_email");

                    b.HasIndex("SellerKey")
                        .IsUnique()
                        .HasDatabaseName("ix_sellers_seller_key");

                    b.ToTable("sellers", (string)null);
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.SellerDailyStats", b =>
                {
                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("Closed")
                        .HasColumnType("integer")
                        .HasColumnName("closed");

                    b.Property<int>("Demos")
                        .HasColumnType("integer")
                        .HasColumnName("demos");

                    b.Property<int>("Lost")
                        .HasColumnType("integer")
                        .HasColumnName("lost");

                    b.Property<int>("MessagesFailed")
                        .HasColumnType("integer")
                        .HasColumnName("messages_failed");

                    b.Property<int>("MessagesSent")
                        .HasColumnType("integer")
                        .HasColumnName("messages_sent");

                    b.Property<int>("PlannedCap")
                        .HasColumnType("integer")
                        .HasColumnName("planned_cap");

                    b.Property<int>("Replies")
                        .HasColumnType("integer")
                        .HasColumnName("replies");

                    b.HasKey("SellerId", "Date")
                        .HasName("pk_seller_daily_stats");

                    b.ToTable("seller_daily_stats", (string)null);
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.SellerLocality", b =>
                {
                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("LocalityGid2")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("locality_gid2");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.HasKey("SellerId", "LocalityGid2")
                        .HasName("pk_seller_localities");

                    b.HasIndex("LocalityGid2")
                        .HasDatabaseName("ix_seller_localities_locality_gid2");

                    b.ToTable("seller_localities", (string)null);
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.CompetitorComment", b =>
                {
                    b.HasOne("SalesHub.Core.Domain.Entities.CompetitorPost", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_competitor_comments_competitor_posts_post_id");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.CompetitorPost", b =>
                {
                    b.HasOne("SalesHub.Core.Domain.Entities.Competitor", "Competitor")
                        .WithMany("Posts")
                        .HasForeignKey("CompetitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_competitor_posts_competitors_competitor_id");

                    b.Navigation("Competitor");
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.ConversationMessage", b =>
                {
                    b.HasOne("SalesHub.Core.Domain.Entities.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_messages_leads_lead_id");

                    b.HasOne("SalesHub.Core.Domain.Entities.Seller", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_conversation_messages_sellers_seller_id");

                    b.Navigation("Lead");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.EvolutionInstance", b =>
                {
                    b.HasOne("SalesHub.Core.Domain.Entities.Seller", "Seller")
                        .WithOne("EvolutionInstance")
                        .HasForeignKey("SalesHub.Core.Domain.Entities.EvolutionInstance", "SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evolution_instances_sellers_seller_id");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.Lead", b =>
                {
                    b.HasOne("SalesHub.Core.Domain.Entities.Product", "Product")
                        .WithMany("Leads")
                        .HasForeignKey("ProductKey")
                        .HasPrincipalKey("ProductKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leads_products_product_key");

                    b.HasOne("SalesHub.Core.Domain.Entities.Seller", "Seller")
                        .WithMany("Leads")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_leads_sellers_seller_id");

                    b.Navigation("Product");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.MessageOutbox", b =>
                {
                    b.HasOne("SalesHub.Core.Domain.Entities.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_outbox_leads_lead_id");

                    b.HasOne("SalesHub.Core.Domain.Entities.Seller", "Seller")
                        .WithMany("OutboxItems")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_outbox_sellers_seller_id");

                    b.Navigation("Lead");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.SellerDailyStats", b =>
                {
                    b.HasOne("SalesHub.Core.Domain.Entities.Seller", "Seller")
                        .WithMany("DailyStats")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seller_daily_stats_sellers_seller_id");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.SellerLocality", b =>
                {
                    b.HasOne("SalesHub.Core.Domain.Entities.Locality", "Locality")
                        .WithMany("SellerAssignments")
                        .HasForeignKey("LocalityGid2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seller_localities_localities_locality_gid2");

                    b.HasOne("SalesHub.Core.Domain.Entities.Seller", "Seller")
                        .WithMany("LocalityAssignments")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seller_localities_sellers_seller_id");

                    b.Navigation("Locality");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.Competitor", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.CompetitorPost", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.Locality", b =>
                {
                    b.Navigation("SellerAssignments");
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.Product", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("SalesHub.Core.Domain.Entities.Seller", b =>
                {
                    b.Navigation("DailyStats");

                    b.Navigation("EvolutionInstance");

                    b.Navigation("Leads");

                    b.Navigation("LocalityAssignments");

                    b.Navigation("OutboxItems");
                });
#pragma warning restore 612, 618
        }
    }
}
